name: Build
on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          pio_lib_path: ~/work/Luos


    steps:
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format@1.5.0

    - name: Check out Luos repository
      uses: actions/checkout@v2

    - name: Check for code format
      if: ${{ runner.os != 'Windows' }}
      run: python .github/workflows/run-clang-format.py -r .

    - name: Create env repo
      shell: bash
      run: |
        # Step back and get dependancies
        cd ..

        # Examples
        git clone https://github.com/Luos-io/Examples.git

    - name: Run PlatformIO
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd ../Examples/
        # L0
        platformio run -d Projects/l0/Button
