name: aaa


on:
  workflow_dispatch:
  #push:
  #  branches-ignore:
  #    - master
  
jobs:
  aaa:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos
        - os: macos-latest
          pio_lib_path: ~/work/Luos
        - os: ubuntu-latest
          pio_lib_path: ~/work/Luos


    steps:
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format@1.5.0

    - name: Check out Luos repository
      uses: actions/checkout@v2


    - name: Create env repo
      shell: bash
      run: |
        # Save branch name


        # Step back and get dependancies
        cd ..


    - name: Run Unit Test Tx

      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd ../Luos/
        platformio run -t clean        
        platformio test -e native -v --filter "transmission"
        
    - name: Run Unit Test mem alloc static
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd ../Luos/
        platformio run -t clean        
        platformio test -e native -v --filter "memory_allocator_static"



  bbb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos
    steps:
        
    - name: LS
      shell: bash
      run: |
        ls
