name: aaa

on:
  push:
    branches-ignore:
      - master
  

jobs:

  abc:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos
        - os: macos-latest
          pio_lib_path: ~/work/Luos
        - os: ubuntu-latest
          pio_lib_path: ~/work/Luos


    steps:
        
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format@1.5.0

    - name: Check out Luos repository
      uses: actions/checkout@v2

    - name: Check for code format
      if: ${{ runner.os != 'Windows' }}
      run: python .github/workflows/run-clang-format.py -r .

    - name: Create env repo
      shell: bash
      run: |
        # Save branch name
        branch_name=unit_test_tx_rx
        origine_branch_name="origin/${branch_name}"
        echo current branch name is ${branch_name}

        # Step back and get dependancies
        cd ..

        # LuosHAL
        git clone https://github.com/Rakadar33/LuosHAL.git
        cd LuosHAL
        cd ..

        # Examples
        git clone https://github.com/Luos-io/Examples.git
        cd Examples
        if [ `git branch -r --list $origine_branch_name` ]
        then
          echo A dependant branch have been found on Examples
          git checkout $branch_name
        else
          echo use master branch on Examples
        fi
        cd ..

    - name: Run PlatformIO
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd ../Examples/
        # L0
        platformio run -d Projects/l0/Button

    - name: Run PlatformIO Unit Tests
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd ../Luos/
        platformio run -t clean        
        platformio test -e native -v --filter "memory_allocator_static"
        platformio test -e native -v --filter "transmission"        

