name: TEST TO DELETE

on:
  workflow_dispatch:

jobs:
  dev-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            pio_lib_path: D:\a\Luos

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          npm install -g clang-format@1.5.0

      - name: Check out Luos repository
        uses: actions/checkout@v2

      - name: Get Luos Engine
        run: |
          dir /ad
          D:
          dir /ad
          cd D:\a\Luos
          dir /ad
          git clone https://github.com/Luos-io/Luos_engine.git
          dir /ad
          cd Luos_engine
          dir /ad

      - name: Run PlatformIO
        run: |
          # L0
          platformio run -d examples/projects/l0/button

      - name: Run PlatformIO Unit Tests
        env:
          PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
        if: ${{ runner.os == 'Windows' }}
        run: |
          # Clean all projects
          platformio run -t clean -c .\test\_resources\platformio.ini

          # Run Unit tests
          platformio test -c .\test\_resources\platformio.ini `
          -f msg_alloc `
          -f luos `
          -f routing_table `
          -f timestamp
